#pragma once

#ifndef MOVECLASS_H
#define MOVECLASS_H

enum MoveCase
{
	NOT_DETERMINED = -1,
	SUCCESSFUL_MOVE = 0,
	VALID_MOVE_ATE_PIECE = 1,
	INVALID_MOVE_NO_PIECE = 2,
	INVALID_MOVE_PIECE_OF_PLAYER = 3,
	INVALID_MOVE_CAUSE_CHECK = 4,
	INVALID_MOVE_OUT_OF_BOUNDS = 5,
	INVALID_MOVE_ILLEGAL_MOVE = 6,
	INVALID_MOVE_SAME_POS = 7,
	VALID_MOVE_CHECKMATE = 8,
	VALID_MOVE_PROMOTION = 9
};

#endif // !MOVECLASS_H